### ISSUE TITLE
"head" property does not seem to be honored

### ISSUE THREAD

**Issue by pastoul** [pitaj/multi-progress#8] opened 2017-09-17 13:47 UTC
const barOptions = {
            head: ">", // this character never shows up
            complete: "=",
            incomplete: " ",
            width: 40,
            total: tickCount};

**Comment by pitaj** [comment] 2017-09-17 17:14
https://github.com/pitaj/multi-progress/blob/master/multi-progress.js#L40

```js
var bar = new ProgressBar(schema, options);
```

The options object is passed straight to progressbar. Maybe the issue is that `head` is a new feature and the dependency on progressbar needs to be updated?

**Comment by pitaj** [comment] 2017-09-17 17:30
Yep, looks like it was added 9 months ago:

https://github.com/visionmedia/node-progress/commit/407ce637242b02c4ccd8a397a71e8b4b85c70720

**Comment by pitaj** [comment] 2020-06-09 04:40
Fixed in multi-progress@3

**Closed as completed by pitaj** 2020-06-09 04:40 UTC
